name: grizzly_io
description: Readers and writers for several file formats (CSV, TSV, JSON, YAML, etc)
version: 4.0.0
homepage: https://github.com/Grizzly-dart/grizzly_io

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  duration: ^3.0.12
  js_bindings: ^0.1.2+1

dev_dependencies:
  test:
