name: grizzly_io
description: Readers and writers for several file formats (CSV, TSV, JSON, YAML, etc)
version: 3.0.1
homepage: https://github.com/Grizzly-dart/grizzly_io

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  http: ^0.13.1

dev_dependencies:
  test:
