name: grizzly_io
description: Readers and writers for several file formats (CSV, TSV, JSON, YAML, etc)
version: 0.0.1-dev
homepage: https://github.com/tejainece/grizzly_io.git
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  test: ^0.12.0
